### PR TITLE
Base Accounts with an entry_role

### PR DESCRIPTION
**Pull request by AKoetsier**
This change allows you to have multiple base accounts with the same account-id / alias but with a different entry role. When using a Identity providers with AWS IAM you often have more than a single role to login to AWS. By specifying an entry_role you can filter accounts based on a base account and role.

### CODE REVIEW

**Comment by sepand** [comment]
any idea when this PR going to get merged? Thanks.

**Comment by robertstettner** [comment]
Friendly bump... we would very much like this!

**Comment by AKoetsier** [comment]
@tilfin anything I can do/help with to get this merged?

**Comment by tilfin** [comment]
@AKoetsier I haven't migrated the tests (test/browser/) to the new UI in V2, so I would like to do that before this PR. The AESR configuration is becoming more and more complex. I want to merge this carefully so that you don't fall into unexpected traps. That will take a lot of time, so I'm behind.

**Comment by tilfin** [comment]
@AKoetsier I think `login_role` is better than `entry_role` since the word 'entry' is not used around AESR. Do you prefer 'entry'?

**Comment by AKoetsier** [comment]
I don't have a specific preference. `login_role` would work as well, just as long as it is clear that it refers to the role that was used initially.

**Comment by tilfin** [comment]
And this implementation will also allow you to filter when you have two users in your AWS Account and log in with each. That makes it possible to set not only IAM role but also IAM user.

**Comment by tilfin** [comment]
I fixed the logic for determining base account so that it can be distinguished from independent target roles. Therefore, it is now possible to define a `role_name` for the **base account** as well, so I decided to use it as a specific field for this feature.

**Pull request merged**
