### PR TITLE
Local storage for external API

### LINKED ISSUE #146: Use local storage instead of sync storage when using the Extension API
I am using the extension API to sync external configs.
Given that the config is syncing to the extension from another extension, it doesn't make sense to use the sync storage to save it.
By using local storage the size limitation for the configs coming from the Extension API could be eliminated.

### PR DESCRIPTION
**Pull request by reegnz**
Fixes #146

### CODE REVIEW

**Comment by reegnz** [comment]
This also fixes #145 and #123 with a caveat, the large configs won't be synced anymore. Still better than not being able to use large configs at all IMHO.

**Comment by reegnz** [comment]
@tilfin I split out the saveAwsConfig function into a separate file because the same logic was used for both updating the config on the options page and through the extension API.

**Comment by TryTryAgain** [comment]
@reegnz have you been able to make this work with the latest updates that moved the accounts list to the extension popup?

**Comment by cmug81** [comment]
Any idea when this will get merged? Pretty much a showstopper for us with a lot of profiles

**Comment by reegnz** [comment]
@TryTryAgain nope, the extension is still only using `chrome.sync` and never `chrome.local`.

https://github.com/tilfin/aws-extend-switch-roles/pull/147/files#diff-becaa957c81c7257d00f1688ea23241ea89eab618f3456abafc4e63e56c5a74bR29

The change I expect is using local storage when configs are coming from an external extension API.

So that `pretty much the same PR` reads as `not the same at all`. ;)

**Comment by reegnz** [comment]
I did a rebase on the current master, and adjusted the code to work with the new popup.
For some reason it's still broken though, so I'll attempt to fix.

**Comment by reegnz** [comment]
Okay now the changes work on HEAD, also removed the mandatory local storage in case of Extension API used.

**Comment by reegnz** [comment]
@tilfin please have a look at this PR and give feedback. This feature is strictly additive in nature, it's not breaking existing functionality.

**Comment by andymac4182** [comment]
@tilfin Any chance of this being merged? It solves some big problems for us.

**Comment by tilfin** [comment]
I am prepared to deal with this issue.

**Comment by andymac4182** [comment]
Thanks @tilfin Happy to help however we can.

**Comment by tilfin** [comment]
This PR feature wil be implemented on #193 and #194.

**Pull request closed without merging**
